---
title: "Docker"
output: html_document
---

You might decide to use another package for your website. 

If you do so and the rendering does not appear to work like usual, this is because that package is not set up in the Docker image that the website template uses to render the files using GitHub Actions. 

For example, you might want to add an interactive table to show some data one a page of your website using the `DT` package like below. 

We will walk through how you could allow for this. 

```{r, echo = FALSE}
DT::datatable(iris, 
          options = list(pageLength = 5), 
          rownames = FALSE
)
```

## Customizing Docker

If you need to have the rendering of your website done by a customized Docker image, you can [follow these instructions to start your own new docker image](https://www.ottrproject.org/customize-docker.html#Starting_a_new_Docker_image).

In summary, you'll need to:

1. Create a new Dockerfile that begins with:

```
FROM jhudsl/course_template:main
```
So that the OTTR required items are incorporated into your new Docker image.

2. After you successfully build this new docker image, you need to push it to Dockerhub so it can be pulled by the OTTR Github actions.

3. Then, in your `config_automation.yml` file, you need to change the `rendering-docker-image:`  spec to be the new docker image's name. 
